# Generated by Django 2.2.7 on 2020-01-03 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='hierarchy',
            field=models.IntegerField(default=0),
        ),
    ]
