# Generated by Django 2.2.7 on 2020-01-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_goal_hierarchy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='hierarchy',
            new_name='parent_id',
        ),
        migrations.AddField(
            model_name='goal',
            name='goal_id',
            field=models.IntegerField(default=0),
        ),
    ]
