# Generated by Django 2.2.7 on 2020-01-04 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_auto_20200104_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='goal_id',
        ),
    ]
