# Generated by Django 2.2.7 on 2020-01-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_remove_goal_goal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='hierarchy_id',
            field=models.FloatField(default=0),
        ),
    ]
