# Generated by Django 2.2.7 on 2020-01-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0005_goal_hierarchy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='depth_id',
            field=models.FloatField(default=0),
        ),
    ]
