# Generated by Django 2.2.7 on 2020-01-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_goal_depth_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='depth_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goal',
            name='hierarchy_id',
            field=models.IntegerField(default=0),
        ),
    ]
