# Generated by Django 2.2.7 on 2020-02-10 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0008_auto_20200210_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='parent_id',
        ),
    ]
