# Generated by Django 2.2.7 on 2020-02-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0011_auto_20200210_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal'),
        ),
    ]
